language: ruby
script: "bundle exec rake validate && bundle exec rake lint"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  allow_failures:
    - rvm: 2.1.0
  fast_finish: true
notifications:
  email: false
  irc:
    channels:
      - "irc.cat.pdx.edu#propuppet"
    template:
      - "#%{build_number} (%{commit} : %{author}): %{message}"
