language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
matrix:
  fast_finish: true
notifications:
  email: false
  irc:
    channels:
      - "irc.cat.pdx.edu#propuppet"
    template:
      - "#%{build_number} (%{commit} : %{author}): %{message}"
